server:
  port: ${PORT}
  address: 0.0.0.0

lavalink:
  server:
    password: "youshallnotpass"

    bufferDurationMs: 1000
    frameBufferDurationMs: 10000
    opusEncodingQuality: 5
    resamplingQuality: MEDIUM
    trackStuckThresholdMs: 10000

    sources:
      youtube: true
      soundcloud: true
      http: true
      local: false

logging:
  level:
    root: INFO
