server:
  port: ${PORT}
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.1"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false

    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.1"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false

  server:
    password: "youshallnotpass"

    bufferDurationMs: 4000
    frameBufferDurationMs: 20000
    opusEncodingQuality: 5
    resamplingQuality: MEDIUM
    trackStuckThresholdMs: 10000

    sources:
      youtube: false
      soundcloud: false
      http: true
      local: false

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true

    clients:
      - M_WEB
      - WEB
      - MUSIC
      - TVHTML5EMBEDDED

    oauth:
      enabled: true
      skipInitialization: false
      # After you get a token, change this section to:
      # enabled: true
      # refreshToken: "YOUR_REFRESH_TOKEN_HERE"
      # skipInitialization: true

  lavasrc:
    providers:
      - "ytsearch:%ISRC% audio"
      - "ytsearch:%QUERY% official audio"
      - "ytsearch:%QUERY% lyric video"
      - "ytsearch:%QUERY% audio"
      - "ytsearch:%QUERY%"

    sources:
      spotify: true

    spotify:
      clientId: "00565b4a154441b9999482ef0fa7537c"
      clientSecret: "cadb9ab0ac5f4e619d7a303bdb99791c"
      countryCode: "GB"

logging:
  level:
    root: INFO
    lavalink: INFO
    dev.lavalink.youtube.http.YoutubeOauth2Handler: DEBUG
