server:
  port: ${PORT}
  address: 0.0.0.0

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      soundcloud: true
      http: true

logging:
  level:
    root: INFO
    lavalink:
  server:
    bufferDurationMs: 800
    frameBufferDurationMs: 10000
